create table PRODUCT (
	PRODUCT_ID BIGINT NOT NULL,
    PRODUCT_NAME VARCHAR(100) NOT NULL,
    PRIMARY KEY(PRODUCT_ID)
);

create table CUSTOMER (
	CUSTOMER_ID BIGINT NOT NULL,
    FIRST_NAME VARCHAR(20) NOT NULL,
    LAST_NAME VARCHAR(20) NOT NULL,
    PRIMARY KEY(CUSTOMER_ID)
);

create table ADDRESS (
	ADDRESS_ID BIGINT NOT NULL,
    STATE VARCHAR(50) NOT NULL,
    CITY VARCHAR(50) NOT NULL,
    COUNTRY VARCHAR(50) NOT NULL,
    ZIP_CODE INT NOT NULL,
    CUSTOMER_ID BIGINT NOT NULL,
    ADDRESS_TYPE VARCHAR(20) NOT NULL,
    PRIMARY KEY(ADDRESS_ID),
    FOREIGN KEY (CUSTOMER_ID) references CUSTOMER(CUSTOMER_ID)
);


create table PHONE_NUMBER (
	PHONE_ID BIGINT NOT NULL,
    PHONE_NUMBER BIGINT NOT NULL,
    IS_DEFAULT BOOLEAN,
    CUSTOMER_ID BIGINT NOT NULL,
    PRIMARY KEY(PHONE_ID),
    FOREIGN KEY (CUSTOMER_ID) references CUSTOMER(CUSTOMER_ID)
);


create table T_ORDER (
	ORDER_ID BIGINT NOT NULL,
    ORDER_DATE DATE NOT NULL,
    CUSTOMER_ID BIGINT NOT NULL,
    PRIMARY KEY(ORDER_ID),
    FOREIGN KEY (CUSTOMER_ID) references CUSTOMER(CUSTOMER_ID)
);



create table PRODUCT_COMMENT (
	COMMENT_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    CUSTOMER_ID BIGINT NOT NULL,
    COMMENT VARCHAR(500) NOT NULL,
    PRIMARY KEY(COMMENT_ID),
    FOREIGN KEY (CUSTOMER_ID) references CUSTOMER(CUSTOMER_ID),
    FOREIGN KEY (PRODUCT_ID) references PRODUCT(PRODUCT_ID)
);



create table ORDER_COMMENT (
	COMMENT_ID BIGINT NOT NULL,
    ORDER_ID BIGINT NOT NULL,
    COMMENT VARCHAR(500) NOT NULL,
    PRIMARY KEY(COMMENT_ID),
    FOREIGN KEY (ORDER_ID) references T_ORDER(ORDER_ID)
    
);

